# Generated by Django 5.0.6 on 2024-06-14 11:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_data_pictures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-data'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'ordering': ['-data'], 'verbose_name': 'рисунок', 'verbose_name_plural': 'рисунки'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 14, 29, 33, 740248), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 14, 29, 33, 741249), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 6, 14, 14, 29, 33, 742248), verbose_name='Дата комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.pictures', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['-data'],
            },
        ),
    ]
